---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: the-recipe-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: the-recipe-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        QUARKUS_LANGCHAIN4J_OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        QUARKUS_DATASOURCE_JDBC_URL: '{{ index . "jdbc-uri" }}'
  dataFrom:
    - extract:
        key: default/the-recipe-db
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-therecipedb
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
