apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SLSKD_API_KEY: ENC[AES256_GCM,data:AfpPa1Ccnoyh5if/Xq0ZXHIqSqL0uYrgv4xApIwTW9fhHqWc/lIjY1GwWwG0KixtPFlbfqi1gsxhuR4wyZEaig==,iv:1s1Ase3bPLqofbwWdIGuTrtk9Z7e8kgzBQPprLwmvds=,tag:T+dfXIiViXuq2u0RixWcxA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jD8Ep4e3TLW2sd2OWPjgem2oyGt1pGOwy0Q=,iv:xC1QMgPhB1nh+uItfMiyc/DzsQsWM60FMcIQ6/zSmw0=,tag:t5TkLXj1YZe83zfZIMhVDg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:dXkgNm7GiSTX2co=,iv:w7OK/7S7cjkBibaReZ1dX1uu3awXZrtnDRaGH8tZcY0=,tag:Q5Tpc3CJEwTXgXxiegJALQ==,type:str]
    SQQ_DOMAIN: ENC[AES256_GCM,data:9WamYZAiYyBmRqH35CN+5X1ClLYDt2MqhWzY,iv:Dq7la+NFYH1jyMCJCwsYSoTI3TLeyw+VyFzGTaQJKOE=,tag:A7orGQqVkPwmB4HPdsZf4g==,type:str]
    LIMITED_DOMAIN: ENC[AES256_GCM,data:7CxY5yxzbzImYhY=,iv:vzZrGtz88rlFEDJ4fg5pHrcqsPV9xyWlYlzWaehIpMo=,tag:D2i2dMuxMmD3ncIvpLhDTA==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:2zgpukzNt+BGnA==,iv:txyqlmKPDtN1RGd+vsz8Xuzos6z7EtvTshOP5pW0pvE=,tag:VRcx9eTjYDDbqpRaYf1h5g==,type:str]
    MATRIX_CLIENT_ID: ENC[AES256_GCM,data:MnR0cz3sjfakbK4lgyQKRZJWWOD44I0L2JR/+bnYCWPeZ1321gx34w==,iv:Vdy2mlsztA9J0HxWet10yg2L8ANR6uhwY2vcWSJCBDI=,tag:unoRjqgykiRAWnrgV//Yew==,type:str]
    MATRIX_CLIENT_SECRET: ENC[AES256_GCM,data:ik2s+Pa9GCx/0+wf/qrgdGdxs4EAwnpmbxnyUlRHex+uHbPihCyASXk4TKfgA+eSmhUJf91BtQvfN/dvm2u1YeNjwydMxKLjuUSNC3aY4wpokaJf8zvCwMpdCp2zP93Ogzex8SfOX7Iaq7DAfSqWo7UNzjaVm+N+7gH5dvzVZtU=,iv:3xcxeNZsES88EcPSd7KxMdqVLkkrmt0+mAhDIDGrtTA=,tag:sL3JC8j7iDc8zfPQs8Jrbg==,type:str]
    SCROBBLE_TOKEN: ENC[AES256_GCM,data:xjI19tFJ5oamAl42qnm4tVxw/G6m5BY3u0z/xvZ4me6U0eQDkhk7+OXyeSI=,iv:sAK+HILwbP3BW67wFIhGdh88xvJoZ53gXQ4mnoQR5LU=,tag:J9JPlbQQh1LJv8ui3A9jVw==,type:str]
sops:
    age:
        - recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvb2tVVWl0TE43bDB2V2Jx
            dThiMXhkbG1PNUZsNEFKNm8zcFUxc05pT0dJCjA2dzhEdlpNSmRPNHBIN1Fuc3Vk
            SDkzYzJaWnE5L2lRSXh2VmdhM0dESmMKLS0tIFV5SFZwS0lMVjEvN2ppN1ZTTmxX
            VU1Pa1ZMazFWZE9HMGVneDhaK1ViMmMKqsQgy1p6qLMacSjnHNZMV7HwQR7RXoBa
            vaO5ZiOO+cMbTrwcd+Gce4U2dhl6AZtUP+ySaw3JZvfcVczW8h45aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T20:06:57Z"
    mac: ENC[AES256_GCM,data:VIXNRPU3QxEd4ZF3AXwYBM3pzQ0iRIc8TYs4t1pbl9BczPxOXgjeDpEecJR3NnDWsE5wrt9oZ3RXF5fPeEsFtvE88IIAsKt62EU1pvkjt0ZLqDDC2glPuc8xPkWEnTWFSuUkBSsi05v9PQzHlojU/cRahj9MpDqk10q8BHoHxd4=,iv:G75lz1sY2Ygx0fULfe1TUGGzgb0k+MbuDqgtXjgvwp4=,tag:QRODNeVxlPrAyIf5dSrLRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
