---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./notifications.yaml
  - ./prowlarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./bazarr/ks.yaml
  - ./slskd/ks.yaml
  - ./betanin/ks.yaml
  - ./navidrome/ks.yaml
  - ./recyclarr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./calibre-web/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellystat/ks.yaml
  - ./piped/ks.yaml
  - ./audiobookshelf/ks.yaml
