---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app keycloak
  namespace: &namespace flux-system
spec:
  targetNamespace: auth
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: keycloak-operator
  path: ./kubernetes/apps/auth/keycloak/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: *namespace
  wait: true
  interval: 1h
  postBuild:
    substitute:
      APP: *app
