---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: actual
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: actual
  ingress:
    - fromEndpoints:
        - matchLabels:
            gateway.envoyproxy.io/owning-gateway-name: external
            io.kubernetes.pod.namespace: network
      toPorts:
        - ports:
            - port: "5006"
              protocol: TCP
