---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitwarden.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./ingress-nginx.yaml
  - ./external-dns.yaml
  - ./hashicorp.yaml
  - ./rook-ceph.yaml
  - ./grafana.yaml
  - ./crunchydata.yaml
  - ./kyverno.yaml
  - ./emberstack.yaml
  - ./userinit-controller.yaml
  - ./k8s-gateway.yaml
  - ./piraeus.yaml
  - ./backube.yaml
  - ./node-feature-discovery.yaml
  - ./emqx.yaml
  - ./bank-vaults.yaml
  - ./codecentric.yaml
  - ./jpgouin.yaml
  - ./bitnami.yaml
  - ./epamedb.yaml
  - ./crowdsec.yaml
  - ./intel.yaml
  - ./nextcloud.yaml
  - ./authentik.yaml
  - ./minecraft.yaml
  - ./fairwinds.yaml
  - ./descheduler.yaml
  - ./actions-runner-controller.yaml
  - ./redpanda.yaml
  - ./strimzi.yaml
  - ./conduktor.yaml
  - ./influxdata.yaml
  - ./kedacore.yaml
  - ./flagsmith.yaml
