---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: keycloak-secret
    template:
      type: Opaque
      data:
        KC_DB_URL: '{{ index . "jdbc-uri" }}'
        KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .KC_BOOTSTRAP_ADMIN_USERNAME }}"
        KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .KC_BOOTSTRAP_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: auth/keycloak
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-keycloakx
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets

