apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-b2-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ZghUlVda3x+N0B6tfF2HLb6Xo2tkNSP0eu4P9MgoHCoxmxViJQGCGmrtexs89Ow50bJJmXUezEJpArI/lGJw2hnDXPQKM9c4drQ=,iv:95kIECBH8kSKk4zGEVRYwQF7CIrFS8ANhRsYuzBXavY=,tag:hIoIBdz1dY7uRZGHuG+1Yg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:eUYYyrXB/NzeV3PPprmjgg==,iv:UulDbzXXlx+W1TXDIXHvhPJHqAngZ0YAxKg0/9xYjZA=,tag:llOpClkyiTDuJgsuHy9r+w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:R89P25xYvUOY8FwI6iH+kvzAOCGfAgGN+Q==,iv:rYYkibH2wFfwVFNOJwBCxE/AAoP9LzdxIGf3EjD78vc=,tag:8JP+5ACpJJp+iDeg3et55w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ux7RVRqqzOUj19RgLWOvg/HCgaCFO65e8UJJs1/YyA==,iv:69PmV/5AoxkqIM9kxv6R2mp2uow1Wnjv1XP54eXavxw=,tag:dDgFl5LBFJOwVfZTAg+0/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDanpDdmZyZjJ0YXNVMWxy
            MXVORVNraU12b3Uvak5MSG93MndxU3A5ZVZFCmZTUmszUFFhWUVjNlVCYU5Rck15
            WmJYemlVbVI1SEVicGRBNit6V0FxOTQKLS0tIDcwN3dwaThJMEVjdnFTSFZYcXFC
            TStaZHJnQnpGemZwVHdJdjk1SmZXaHcKSjKuhXGqjnD+9ajn/XjaVbL25vLuMr2b
            Y6gGmT8R5CyKD2/co1V3M+3XKDLy8DVATjkIy/eXuoBAqO2n+RiFmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T19:36:24Z"
    mac: ENC[AES256_GCM,data:dGzPrxXzo8Ojr4KFuyM1VSAQMRfB/mAXiriQWv1XXaVlvzkxd3riLIkCp9ZbZKOYcQF20LsO4et0atnBzXNbroGA01d8FwR2hpLCxDNaky8Hgck6gcWXH0ze9FXSRzP/90gO3M3aTubXxv0CyZRsANyoLJSkTMpUp/e7qipxFD0=,iv:jWWeN5sNEPhp6XtPkk/SmjF6TFqeApD1XSKUTjX1AG4=,tag:LFRnFlwM8TBOfptIb2U5Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
