apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:DHqiaynRqdYP3BKpVUZUCDF1nmYkVep+q01N7/0jPAkhi1xcrO9Ik+IVqz9vRckm6zWsN48tymDdgTOpOYbTPg==,iv:dTd3m+XzO3cegE09q8X1rvtMcV4RMKkiSQSXmpjkKms=,tag:LVTHNjUdnG2W7ee8RH5ziQ==,type:str]
    KOPIA_FS_PATH: ENC[AES256_GCM,data:3+HC/ANlnK3Ja5U=,iv:OABIkj2C+sugeZUmkXpUJ+/Lv4skJPqsfivWnHRauPY=,tag:gICa7epooBBads73NYzA8Q==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:C87xsdf6uri4zm8EnmLmAbkMvAyVcvPM,iv:ZM6Tasm/A7bi5lUwHRfIUtr3rPENYDqlsH+53C6HB58=,tag:CMMQONDTfdiK1VG9xG6wug==,type:str]
sops:
    age:
        - recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UlY0MHF2WEFFRzV6cTcy
            Tk8rNFpveE5HOVFTK3YyVmFYdDRSVGpsMWdzCitWUTh0dDZ0c1l4OUpiaG00OXh6
            Y2didU01YjVUNUNlbTVtbnZ0RklvNVkKLS0tIG5rakV0Z3hMdHc3dlduU0RZYTFl
            ZGxKc1RPdlB6ZTZuNjlzYWpEU1hxbkEKUP1VL8YdpsuMWIprVQ+6oTo4ARl0i4E4
            M34LJi9cs2v9k8HVVsbtJuC1Mbrw882WdU7gTOkE5M6X4tTZJiOhSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:15:46Z"
    mac: ENC[AES256_GCM,data:zZbcDMAYLrletSmoLckoMzjszwJINiK1KBftOO0eB6z2RcPbR0n88V6Zx6DoYWWel889B6jxYUulCi75CY1KaJ1hjeGHRaCyKnitTrSrZvWV4SdaDlvD9sXTqffXIOA4zOREbxWyVcSIbqklXs7bNALaJT2eNPWftkSroFnaDr8=,iv:2qoBByiA/eneOU12LkmTkraGew+rpUPqojjRTl64aRA=,tag:3eIcxmZw/gUrZ54q2V9t1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
