---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: librechat-credentials-env
    template:
      data:
        CREDS_KEY: "{{ .CREDS_KEY }}"
        CREDS_IV: "{{ .CREDS_IV }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        JWT_REFRESH_SECRET: "{{ .JWT_REFRESH_SECRET }}"
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
  dataFrom:
    - extract:
        key: ai/librechat
