---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore
spec:
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: booklore-secret
    template:
      type: Opaque
      data:
        DATABASE_URL: '{{ index . "jdbc-uri" }}'
  dataFrom:
    - extract:
        key: postgres-16-pguser-booklore
