---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sqq-vente-groupee-staging
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: sqq-vente-groupee-staging-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        STRIPE_API_KEY: "{{ .STRIPE_API_KEY }}"
        STRIPE_WEBHOOK_SECRET: "{{ .STRIPE_WEBHOOK_SECRET }}"
        QUARKUS_DATASOURCE_JDBC_URL: '{{ index . "jdbc-uri" }}'
        QUARKUS_OIDC_AUTH_SERVER_URL: https://sso.${SECRET_DOMAIN}/application/o/sqq-vente-groupee-staging/
        QUARKUS_OIDC_CLIENT_ID: "{{ .CLIENT_ID }}"
        QUARKUS_OIDC_CREDENTIALS_SECRET: "{{ .CLIENT_SECRET }}"
        QUARKUS_OIDC_AUTHENTICATION_FORCE_REDIRECT_HTTPS_SCHEME: "true"
        QUARKUS_OIDC_AUTHENTICATION_PKCE_REQUIRED: "true"
        QUARKUS_OIDC_AUTHENTICATION_REDIRECT_PATH: "/admin"
        APP_BASE_URL: "https://sqq-vente-groupee-staging.${SECRET_DOMAIN}"
  dataFrom:
    - extract:
        key: default/sqq-vente-groupee-staging
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-sqqvg
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
