---
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: homeassistant-mcp
spec:
  description: Grafana MCP server
  protocol: STREAMABLE_HTTP
  sseReadTimeout: 5m0s
  terminateOnClose: true
  timeout: 30s
  url: http://home-assistant.home.svc.cluster.local:8123/api/mcp
