---
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: homeassistant-mcp
spec:
  description: Home Assistant MCP Server
  protocol: STREAMABLE_HTTP
  url: http://home-assistant.home.svc.cluster.local:8123/api/mcp
  headersFrom:
    - name: Authorization
      valueFrom:
        name: kagent-secret
        key: HOMEASSISTANT_AUTH_HEADER
        type: Secret
