---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
components:
  - ../../components/common
resources:
  - ./authentik/ks.yaml
  - ./keycloak/ks.yaml
  - ./keycloak-operator/ks.yaml
