---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./echo-server/ks.yaml
  - ./miniflux/ks.yaml
  - ./changedetection/ks.yaml
  - ./atuin/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./actual/ks.yaml
  - ./wallabag/ks.yaml
  - ./immich/ks.yaml
  - ./homelab-manager/ks.yaml
  - ./nextcloud/ks.yaml
  - ./bytestash/ks.yaml
  - ./sftpgo/ks.yaml
  - ./thelounge/ks.yaml
  - ./outline/ks.yaml
  - ./grist/ks.yaml
  - ./vikunja/ks.yaml
  - ./habittrove/ks.yaml
  - ./paperless/ks.yaml
  - ./n8n/ks.yaml
  - ./sqq-inscription/ks.yaml
  - ./rustical/ks.yaml
  - ./bichon/ks.yaml
  - ./manyfold/ks.yaml
  - ./the-recipe-db/ks.yaml
