---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sqq-sondages
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: sqq-sondages-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        QUARKUS_DATASOURCE_JDBC_URL: '{{ index . "jdbc-uri" }}'
  dataFrom:
    - extract:
        key: postgres-16-pguser-sqqsondages
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
