apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:dRuD8biH29uqQBymRM8Y2ChpE2ZeroBSkkd3MB4jsaycfldalOKCxqIyHaOk3TlFh5PvdMpZE2SmtAIXhDrGHA==,iv:7gQ/ZhQY1SopYzsTdMnTtMrmK4wd1Ynp35XutI9tliE=,tag:Ew9ZS69Y6/imERVmI7XO7g==,type:str]
    KOPIA_FS_PATH: ENC[AES256_GCM,data:DUN1sLzRo4pcuKI=,iv:RHgTVM6eZdrDEJA9FGjErihRF754kz4S139uIFXD27Q=,tag:3zbcvlQk0JDEtRq2lfr2Tw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:89GBO75haptQjlUjLUOufAdW9aCAkZu9,iv:/HHXVqutiV/OzzGTKM8zbT/Y3xg1SKRJdn+2/3wGcfY=,tag:+FfjrURFwDoadP/H1tbapA==,type:str]
sops:
    age:
        - recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSGZ0dnVrQ1ZYWWdRRjY0
            OWtFMEJyTmpvOE1QR29UdXFsZnVTZXFQTEhRCldjWGR6UEFMNjdhZ252dVRONGMr
            V2NsZG8wR0FkM3l3Uk42SU9HemsxeGcKLS0tIDQveXpLVU9oZHM2RllpUjRXN0Fj
            dlE2SDJBVEVaQllDSmRoOElEMFNWSEUKu4uYpVAhhcH2d+4qtEruA2xSRWS2FTNe
            hpk99irpvCtA3RCQ7UhRH7zpOkE3aBrFq/h5RnfyLRue3bUXQPOycQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:39:14Z"
    mac: ENC[AES256_GCM,data:8S5YILQpivtkH6lhzmijWwUnmGociVnZA/FybqWHTNH+V9V4zPRw25Rm9qOURlF3tDwSwlomgRJ5EV1ktV+CP11VRJYk7rosBhbmX9BczejrIw3MnEQkO2oiPIYBXPDpIA8hVjdOwboQzHxWI0T9IUVJuu6j2xnqRpsEHpB3GGA=,iv:tzdy/FiG4/5R2k5UjzvvXFSxbqLyJp3ohTCKvJxmjo0=,tag:3hJaa7OuxpI9goaUQUePSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
