---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readur
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: readur-secret
    template:
      engineVersion: v2
      data:
        # Database
        DATABASE_URL: "{{ .pg_uri }}"
        # App
        JWT_SECRET: "{{ .JWT_SECRET }}"
        # OIDC
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_REDIRECT_URI: "https://readur.${LIMITED_DOMAIN}/api/auth/oidc/callback"
        OIDC_ISSUER_URL: "https://sso.${SECRET_DOMAIN}/application/o/readur/"
        OIDC_AUTO_REGISTER: "true"
        ALLOW_LOCAL_AUTH: "false"
  dataFrom:
    - extract:
        key: default/readur
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-readur
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
