---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./exporters
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./loki/ks.yaml
  - ./alloy/ks.yaml
  - ./kromgo/ks.yaml
  - ./gatus/ks.yaml
  - ./keda/ks.yaml
  #- ./silence-operator/ks.yaml
  - ./karma/ks.yaml
  - ./tempo/ks.yaml
  - ./umami/ks.yaml
