---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: not-found-page
spec:
  directResponse:
    contentType: text/plain
    statusCode: 404
    body:
      type: Inline
      inline: "Vade Retro, Satanas!"
