apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:klViyQsa53wR/UCBHOoHV9LzClJ0yrzfVTSA3chZxq46M7mB6kOuZrvBkhzFTmPAgG8ihGE31nvZSkWAaZcsYA==,iv:l39iiNH+mJT4a7NPdBmQ9KhUmiFlzwQ33ODm6SEmFyk=,tag:0P2oe+MeZA3zHTw2js2xeQ==,type:str]
sops:
    age:
        - recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dUhSM28wNk1oa3hoc0t3
            UUR2eGppWGkyaURrVFE4cWUrdXVkOFA4NkJRCjlDUWo5QW9rUUxVTHFhTUhQbkYx
            R3hxbDlDKzdPaVlwSWExcldXeExJWHcKLS0tIGt3ZzRlZFh2SjlTNFlrSEVWbUVv
            cXl0ZFF2SkE2UXBsQ25Cd2hWUDNiU3cK+hCtFxpRmqsvk4upnK0DQok7K5Qt3ugy
            Je3/Zgl8OtuadNMTtjXTNVFi0Lyi/tWV/1PjQVkgbaIocFTYUQG7Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:48:14Z"
    mac: ENC[AES256_GCM,data:MAIfjQXInEkpQcUTd2SuUyZOrxYE/gpihX2gxwoT8tB6vrgNxDNAwHE7wcPsF8TP+JfoaSf5BfQjn1FTrg/SijTVJiDAkSCBmBE3BZb+2hLoA9GwLJOUmtpnO0DrPiGsiUqgcsT8c43OJAl8Go+1TrhdyTkojFFuWRdu7qutlW4=,iv:zmdIpIVUgmCGdHiD1zoVBZKSDm+lF8z0ndp8NKpNmrs=,tag:Og6R4BF72R9b/bOslFfNkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
