---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sqq-inscription-staging
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: sqq-inscription-staging-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        STRIPE_API_KEY: "{{ .STRIPE_API_KEY }}"
        STRIPE_PART_SOCIALE_PRICE_ID: "{{ .STRIPE_PART_SOCIALE_PRICE_ID }}"
        STRIPE_REDIRECT_DOMAIN: https://souscription-staging-superquinquin-sur-deule.${SECRET_DOMAIN}
        QUARKUS_DATASOURCE_JDBC_URL: '{{ index . "jdbc-uri" }}'
        QUARKUS_SECURITY_USERS_EMBEDDED_USERS_admin: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: default/sqq-inscription-staging
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-sqqstaging
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
