---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustical
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: rustical-secret
    template:
      engineVersion: v2
      data:
        RUSTICAL_HTTP__HOST: "::"
        RUSTICAL_FRONTEND__ALLOW_PASSWORD_LOGIN: "false"
        RUSTICAL_OIDC__NAME: "SSO"
        RUSTICAL_OIDC__ISSUER: "https://sso.${SECRET_DOMAIN}/application/o/rustical/"
        RUSTICAL_OIDC__CLIENT_ID: "{{ .RUSTICAL_OIDC__CLIENT_ID }}"
        RUSTICAL_OIDC__CLIENT_SECRET: "{{ .RUSTICAL_OIDC__CLIENT_SECRET }}"
        RUSTICAL_OIDC__CLAIM_USERID: "preferred_username"
        RUSTICAL_OIDC__SCOPES: '["openid", "profile", "offline_access"]'
        RUSTICAL_OIDC__ALLOW_SIGN_UP: "true"
  dataFrom:
    - extract:
        key: default/rustical
